# Generated by Django 5.0.6 on 2026-05-17 22:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntuneConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntunePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('policy_type', models.CharField(choices=[('device_configuration', 'Device Configuration'), ('compliance', 'Compliance'), ('app_protection', 'App Protection'), ('enrollment', 'Enrollment'), ('security_baseline', 'Security Baseline')], max_length=30)),
                ('json_payload', models.JSONField(default=dict)),
                ('is_deployed', models.BooleanField(default=False)),
                ('last_deployed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='products.intuneconfig')),
            ],
            options={
                'verbose_name_plural': 'Intune policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('recast_workspace', 'Recast Application Workspace'), ('windows_365', 'Windows 365 Cloud PC'), ('intune', 'Microsoft Intune')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('provisioning', 'Provisioning'), ('error', 'Error')], default='provisioning', max_length=20)),
                ('enabled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organisations.organisation')),
            ],
            options={
                'ordering': ['product_type'],
                'unique_together': {('organisation', 'product_type')},
            },
        ),
        migrations.AddField(
            model_name='intuneconfig',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intune_config', to='products.productinstance'),
        ),
        migrations.CreateModel(
            name='RecastWorkspaceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_url', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
                ('workspace_id', models.CharField(blank=True, max_length=100)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(blank=True, max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recast_config', to='products.productinstance')),
            ],
        ),
        migrations.CreateModel(
            name='Windows365Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provisioning_policy_id', models.CharField(blank=True, max_length=100)),
                ('user_settings_id', models.CharField(blank=True, max_length=100)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='windows365_config', to='products.productinstance')),
            ],
        ),
        migrations.CreateModel(
            name='CloudPC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph_id', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('user_principal_name', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('provisioned', 'Provisioned'), ('provisioning', 'Provisioning'), ('deprovisioning', 'Deprovisioning'), ('failed', 'Failed'), ('not_provisioned', 'Not Provisioned')], max_length=30)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_pcs', to='products.windows365config')),
            ],
        ),
    ]
