# Generated by Django 5.1.15 on 2026-05-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_update_membership_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environmentmembership',
            options={'ordering': ['environment', 'role']},
        ),
    ]
