# Generated by Django 5.1.15 on 2026-05-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0004_environment_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environment',
            options={'ordering': ['sort_order', 'name']},
        ),
    ]
