# Generated by Django 5.1.15 on 2026-05-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_date_joined_and_more'),
        ('accounts', '0002_update_roles'),
    ]

    operations = [
    ]
