# Generated by Django 5.1.15 on 2026-05-19 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('recast_workspace', 'Recast Application Workspace'), ('recast_user_license', 'Recast Application Workspace User License'), ('windows_365', 'Windows 365 Cloud PC'), ('intune', 'Microsoft Intune')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('configuring', 'Configuring'), ('error', 'Error')], default='configuring', max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='environments.environment')),
            ],
            options={
                'unique_together': {('environment', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='RecastConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField()),
                ('api_key', models.CharField(max_length=500)),
                ('workspace_count', models.PositiveIntegerField(default=0)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recast_config', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='IntuneConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=200)),
                ('tenant_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(blank=True, max_length=500)),
                ('policy_json', models.JSONField(blank=True, default=dict)),
                ('last_deployed', models.DateTimeField(blank=True, null=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intune_config', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='Windows365Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=200)),
                ('tenant_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(blank=True, max_length=500)),
                ('device_count', models.PositiveIntegerField(default=0)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='w365_config', to='services.service')),
            ],
        ),
    ]
