# Generated by Django 5.1.15 on 2026-05-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['environment', 'service_type', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, help_text='Optional display name. Defaults to the service type name if left blank.', max_length=200),
        ),
    ]
