# Generated by Django 5.1.15 on 2026-05-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options_alter_service_unique_together_and_more'),
        ('services', '0002_recast_license_workflow'),
    ]

    operations = [
    ]
