# Generated by Django 5.1.15 on 2026-05-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_merge_20260521_1249'),
        ('services', '0003_remove_recast_user_license'),
    ]

    operations = [
    ]
