# Generated by Django 5.1.15 on 2026-05-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_sort_order'),
        ('services', '0004_merge_20260521_1818'),
    ]

    operations = [
    ]
