# Generated by Django 5.1.15 on 2026-05-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_merge_20260524_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('recast_workspace', 'Recast Workspace'), ('windows_365', 'Windows 365'), ('intune', 'Intune')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('configuring', 'Configuring'), ('active', 'Active'), ('error', 'Error'), ('inactive', 'Inactive')], default='configuring', max_length=20),
        ),
    ]
