# Generated by Django 5.1.15 on 2026-05-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_logo_dark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo_dark',
        ),
    ]
