# Generated by Django 5.1.15 on 2026-05-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sitesettings_logo_dark'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Logo for dark theme. If left empty, the default logo is used for both themes.', null=True, upload_to='branding/'),
        ),
    ]
